### ISSUE TITLE
[SLD-Parser] Complex Polygons are not parsed

### ISSUE THREAD

**Issue by chrismayer** [geostyler/geostyler-sld-parser#249]
Currently the `sld-parser` only parses the fill and stroke property of the polygons in a `sld` rule and doesn't  consider other `cssParameter`s such as `stroke-dasharray` or `GraphicFill`. In addition the parser fails to consider multiple `PolygonSymbolizer`s. 

[Example Sld](https://gist.github.com/amir-ba/a5558020403eeb94cd5953170252d34c) is a sample `SLD` that the parser needs to be able to parse. 

Sub-issues / related issues to complete this:

- [x] Support for pattern fill in FillSymbolizer https://github.com/terrestris/geostyler/issues/214
- [x] Support for multiple symbolizers (gs-style) https://github.com/terrestris/geostyler/issues/248
- [x] Support multiple symbolizer (SLD-Parser) https://github.com/terrestris/geostyler/issues/85 
- [x] Support for further cssParameters https://github.com/terrestris/geostyler/issues/249

**Comment by KaiVolland** [comment]
https://github.com/geostyler/geostyler/pull/372
